server {
    root /usr/share/nginx/html;
    index index.html;
    location /api/ {
        proxy_pass http://server-prod:5200/;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}